server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/dbapp2?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
  tokenurl: http://kong-internal-proxy.system:10083
  servlet:
    multipart:
      max-file-size: 20000MB
      max-request-size: 20000MB

  banner:
    location: ["classpath:banner.txt", "file:./banner.txt"]
  freemarker:
    cache: false
    settings:
      template_exception_handler: rethrow
      number_format: 0.##
    template-loader-path: ["classpath:/templates/", "file:./templates/"]
  messages:
    basename: i18n/message

#  resources:
#    static-locations: ["classpath:static/", "file:./static/"]

# 配置mapper.xml位置，这个位置可以在pom.xml里配置
mybatis-plus:
  mapper-locations: classpath:/*Mapper.xml
